export type FantasyPlayer = { name: string; role: string; ipl: string; price?: number };
export type FantasyTeam = {
  id: string; name: string; owner: string; emoji: string; color: string;
  avatar: string;
  avatarPosition?: string;
  captain: string; vc: string;
  players: FantasyPlayer[];
};

export const FANTASY_TEAMS: Record<string, FantasyTeam> = {
  rajveer: {
    id: "rajveer", name: "Jay Shah Supremacy", owner: "Raj", emoji: "🏏", color: "#f97316",
    avatar: "raj.jpeg", avatarPosition: "center center",
    captain: "Rajat Patidar", vc: "Axar Patel",
    players: [
      { name: "Rajat Patidar", role: "BAT", ipl: "RCB", price: 7 },
      { name: "Axar Patel", role: "AR", ipl: "DC", price: 7 },
      { name: "Shubman Gill", role: "BAT", ipl: "GT", price: 14 },
      { name: "Jos Buttler", role: "WK", ipl: "GT", price: 7 },
      { name: "Yuzvendra Chahal", role: "BWL", ipl: "PBKS", price: 2 },
      { name: "Jacob Bethell", role: "AR", ipl: "RCB", price: 2.5 },
      { name: "Bhuvneshwar Kumar", role: "BWL", ipl: "RCB", price: 5 },
      { name: "Shreyas Iyer", role: "BAT", ipl: "PBKS", price: 14 },
      { name: "Cameron Green", role: "AR", ipl: "KKR", price: 12 },
      { name: "Nicholas Pooran", role: "WK", ipl: "LSG", price: 10.5 },
      { name: "Phil Salt", role: "WK", ipl: "RCB", price: 14 },
      { name: "Krunal Pandya", role: "AR", ipl: "RCB", price: 6 },
      { name: "Priyansh Arya", role: "BAT", ipl: "PBKS", price: 6.5 },
      { name: "Vaibhav Suryavanshi", role: "BAT", ipl: "RR", price: 5 },
      { name: "Dhruv Jurel", role: "WK", ipl: "RR", price: 0.5 },
      { name: "Mohammed Shami", role: "BWL", ipl: "LSG", price: 0.5 },
      { name: "Tim David", role: "BAT", ipl: "RCB", price: 0.5 },
      { name: "Deepak Chahar", role: "BWL", ipl: "MI", price: 36 },
    ],
  },
  mombasa: {
    id: "mombasa", name: "Mombasa Kenyans", owner: "Rahul", emoji: "⚡", color: "#eab308",
    avatar: "rahul.jpeg", avatarPosition: "center 30%",
    captain: "Abhishek Sharma", vc: "Sai Sudharsan",
    players: [
      { name: "Jitesh Sharma", role: "WK", ipl: "RCB", price: 6.5 },
      { name: "Varun Chakravarthy", role: "BWL", ipl: "KKR", price: 8 },
      { name: "Marco Jansen", role: "AR", ipl: "PBKS", price: 4.5 },
      { name: "Arshdeep Singh", role: "BWL", ipl: "PBKS", price: 15 },
      { name: "Shivam Dube", role: "AR", ipl: "CSK", price: 10 },
      { name: "Riyan Parag", role: "BAT", ipl: "RR", price: 6 },
      { name: "Abhishek Sharma", role: "AR", ipl: "SRH", price: 15.5 },
      { name: "Prabhsimran Singh", role: "WK", ipl: "PBKS", price: 6 },
      { name: "Nehal Wadhera", role: "BAT", ipl: "PBKS", price: 1 },
      { name: "Shimron Hetmyer", role: "BAT", ipl: "RR", price: 3.5 },
      { name: "Sai Sudharsan", role: "BAT", ipl: "GT", price: 8 },
      { name: "Will Jacks", role: "AR", ipl: "MI", price: 10 },
      { name: "Prasidh Krishna", role: "BWL", ipl: "GT", price: 4.5 },
      { name: "Aiden Markram", role: "AR", ipl: "LSG", price: 9 },
      { name: "Rashid Khan", role: "AR", ipl: "GT", price: 8.5 },
      { name: "Ajinkya Rahane", role: "BAT", ipl: "KKR", price: 3 },
      { name: "Trent Boult", role: "BWL", ipl: "MI", price: 4.5 },
      { name: "Tilak Varma", role: "AR", ipl: "MI", price: 26.5 },
    ],
  },
  mumbai: {
    id: "mumbai", name: "Mumbai Mavericks", owner: "Smeet", emoji: "🌊", color: "#3b82f6",
    avatar: "smeet.jpeg", avatarPosition: "center 35%",
    captain: "Hardik Pandya", vc: "Sanju Samson",
    players: [
      { name: "Rishabh Pant", role: "WK", ipl: "LSG", price: 10 },
      { name: "Dewald Brevis", role: "BAT", ipl: "CSK", price: 3.5 },
      { name: "Rohit Sharma", role: "BAT", ipl: "MI", price: 7 },
      { name: "Sherfane Rutherford", role: "BAT", ipl: "MI", price: 2 },
      { name: "Rinku Singh", role: "BAT", ipl: "KKR", price: 1.5 },
      { name: "Heinrich Klaasen", role: "WK", ipl: "SRH", price: 5 },
      { name: "Nitish Rana", role: "BAT", ipl: "DC", price: 1 },
      { name: "Ruturaj Gaikwad", role: "WK", ipl: "CSK", price: 3.5 },
      { name: "Lungi Ngidi", role: "BWL", ipl: "DC", price: 1 },
      { name: "Mohammed Siraj", role: "BWL", ipl: "GT", price: 1.5 },
      { name: "Harshal Patel", role: "BWL", ipl: "SRH", price: 1 },
      { name: "Tristan Stubbs", role: "BAT", ipl: "DC", price: 3.5 },
      { name: "Sanju Samson", role: "WK", ipl: "CSK", price: 20 },
      { name: "Prashant Veer", role: "AR", ipl: "CSK", price: 1 },
      { name: "Ishan Kishan", role: "WK", ipl: "SRH", price: 16.5 },
      { name: "Hardik Pandya", role: "AR", ipl: "MI", price: 30 },
      { name: "Finn Allen", role: "BAT", ipl: "KKR", price: 20 },
      { name: "Venkatesh Iyer", role: "AR", ipl: "RCB", price: 22 },
    ],
  },
  ponygoat: {
    id: "ponygoat", name: "PonyGoat", owner: "Deb", emoji: "🐐", color: "#10b981",
    avatar: "deb.jpeg", avatarPosition: "center 30%",
    captain: "Sunil Narine", vc: "Jasprit Bumrah",
    players: [
      { name: "Marcus Stoinis", role: "AR", ipl: "PBKS", price: 1.5 },
      { name: "Yashasvi Jaiswal", role: "BAT", ipl: "RR", price: 19 },
      { name: "Tim Seifert", role: "WK", ipl: "KKR", price: 1 },
      { name: "Virat Kohli", role: "BAT", ipl: "RCB", price: 16 },
      { name: "Shashank Singh", role: "AR", ipl: "PBKS", price: 3.5 },
      { name: "Sunil Narine", role: "AR", ipl: "KKR", price: 13.5 },
      { name: "Suryakumar Yadav", role: "BAT", ipl: "MI", price: 20.5 },
      { name: "Jasprit Bumrah", role: "BWL", ipl: "MI", price: 19.5 },
      { name: "Ravindra Jadeja", role: "AR", ipl: "RR", price: 9.5 },
      { name: "Travis Head", role: "BAT", ipl: "SRH", price: 11.5 },
      { name: "KL Rahul", role: "WK", ipl: "DC", price: 10 },
      { name: "Ryan Rickelton", role: "WK", ipl: "MI", price: 7 },
      { name: "Mitchell Marsh", role: "AR", ipl: "LSG", price: 11.5 },
      { name: "Khaleel Ahmed", role: "BWL", ipl: "CSK", price: 1 },
      { name: "Kuldeep Yadav", role: "BWL", ipl: "DC", price: 3 },
      { name: "Washington Sundar", role: "AR", ipl: "GT", price: 1 },
      { name: "T Natarajan", role: "BWL", ipl: "DC", price: 1 },
    ],
  },
};
